apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: yunez
    app-code: nu0445001
  name: yunez
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-2048
  namespace: yunez
spec:
  template:
    metadata:
      labels:
        app-code: nu0445001
    spec:
      containers:
      - name: app-2048
        image: public.ecr.aws/l6m2t8p7/docker-2048:latest
        ports:
          - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app-code: nu0445001
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-2048
  namespace: yunez
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app-code: nu0445001